services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: lorville
      POSTGRES_PASSWORD: passw
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: aprilfrommay444@gmail.com
      PGADMIN_DEFAULT_PASSWORD: lorvillepgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
