services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: spotify
      POSTGRES_USER: dev
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
